all:
	g++ -g --std=c++0x -o multi-thread-example multi-thread-example.cc -I../src -lpthread -L../lib/ -lringlog
	g++ -g --std=c++0x -o single-thread-example single-thread-example.cc -I../src -lpthread -L../lib/ -lringlog
